import { NgModule } from '@angular/core';
import {
    MatButtonModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatInputModule,
    MatSnackBarModule,
    MatFormFieldModule,
    MatGridListModule,
    MatDialogModule,
    MatSelectModule,
    MatTableModule,
    MatMenuModule,
    MatAutocompleteModule,
    MatTabsModule,
    MatExpansionModule,
    MatListModule,
    MatProgressBarModule,
} from '@angular/material';

@NgModule({
    imports: [
        MatButtonModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatIconModule,
        MatCardModule,
        MatInputModule,
        MatSnackBarModule,
        MatFormFieldModule,
        MatGridListModule,
        MatDialogModule,
        MatSelectModule,
        MatTableModule,
        MatMenuModule,
        MatAutocompleteModule,
        MatTabsModule,
        MatExpansionModule,
        MatListModule,
        MatProgressBarModule
    ],
    exports: [
        MatButtonModule,
        MatCheckboxModule,
        MatToolbarModule,
        MatIconModule,
        MatCardModule,
        MatInputModule,
        MatSnackBarModule,
        MatFormFieldModule,
        MatGridListModule,
        MatDialogModule,
        MatSelectModule,
        MatTableModule,
        MatMenuModule,
        MatAutocompleteModule,
        MatTabsModule,
        MatExpansionModule,
        MatListModule,
        MatProgressBarModule
    ]
})
export class AngularMaterialModule { }
