<?xml version='1.0' ?>
<xsl:stylesheet xmlns:xsl='http://www.w3.org/1999/XSL/Transform' version='1.0'>
  <xsl:template match='/EmailMessage'>
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse: separate;mso-table-lspace: 0pt;mso-table-rspace: 0pt;width: 100%;background-color: #f6f6f6;">
      <tbody>
        <tr>
          <td style="font-family: sans-serif;font-size: 14px;vertical-align: top;"> </td>
          <td class="container" style="font-family: sans-serif;font-size: 14px;vertical-align: top;display: block;max-width: 580px;padding: 10px;width: 580px;margin: 0 auto !important;">
            <div class="content" style="box-sizing: border-box;display: block;margin: 0 auto;max-width: 580px;padding: 10px;">

              <!-- START CENTERED WHITE CONTAINER -->
              <span class="preheader" style="color: transparent;display: none;height: 0;max-height: 0;max-width: 0;opacity: 0;overflow: hidden;mso-hide: all;visibility: hidden;width: 0;">
                This
                is preheader text. Some clients will show this text as a preview.
              </span>
              <table role="presentation" class="main" style="border-collapse: separate;mso-table-lspace: 0pt;mso-table-rspace: 0pt;width: 100%;background: #ffffff;border-radius: 3px;">

                <!-- START MAIN CONTENT AREA -->
                <tbody>
                  <tr>
                    <td class="wrapper" style="font-family: sans-serif;font-size: 14px;vertical-align: top;box-sizing: border-box;padding: 20px;">
                      <table role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate;mso-table-lspace: 0pt;mso-table-rspace: 0pt;width: 100%;">
                        <tbody>
                          <tr>
                            <td style="font-family: sans-serif;font-size: 14px;vertical-align: top;">
                              <p style="font-family: sans-serif;font-size: 14px;font-weight: normal;margin: 0;margin-bottom: 15px;">
                                Hi <xsl:value-of select='UserName' />,
                              </p>
                              <p style="font-family: sans-serif;font-size: 14px;font-weight: normal;margin: 0;margin-bottom: 15px;">
                                This
                                mail was autogenerated because someone created account
                                for this
                                email. If you want to confirm your account, please click
                                the button
                                below.
                              </p>
                              <table role="presentation" border="0" cellpadding="0"
                                  cellspacing="0" class="btn btn-primary" style="border-collapse: separate;mso-table-lspace: 0pt;mso-table-rspace: 0pt;width: 100%;box-sizing: border-box;">
                                <tbody>
                                  <tr>
                                    <td align="left" style="font-family: sans-serif;font-size: 14px;vertical-align: top;padding-bottom: 15px;">
                                      <table role="presentation" border="0"
                                          cellpadding="0" cellspacing="0" style="border-collapse: separate;mso-table-lspace: 0pt;mso-table-rspace: 0pt;width: auto;">
                                        <tbody>
                                          <tr>
                                            <td style="font-family: sans-serif;font-size: 14px;vertical-align: top;background-color: #3498db;border-radius: 5px;text-align: center;">
                                              <xsl:element name="a">
                                                <xsl:attribute name="href">
                                                  <xsl:value-of select='CallbackUrl' />
                                                </xsl:attribute>
                                                <xsl:attribute name="style">
                                                  color:
                                                  #ffffff;text-decoration:
                                                  none;background-color:
                                                  #3498db;border: solid
                                                  1px
                                                  #3498db;border-radius:
                                                  5px;box-sizing:
                                                  border-box;cursor:
                                                  pointer;display:
                                                  inline-block;font-size:
                                                  14px;font-weight:
                                                  bold;margin: 0;padding:
                                                  12px
                                                  25px;text-transform:
                                                  capitalize;border-color:
                                                  #3498db;
                                                </xsl:attribute>
                                                Confirm you account
                                              </xsl:element>
                                            </td>
                                          </tr>
                                        </tbody>
                                      </table>
                                    </td>
                                  </tr>
                                </tbody>
                              </table>
                              <p style="font-family: sans-serif;font-size: 14px;font-weight: normal;margin: 0;margin-bottom: 15px;">
                                If
                                you did not create this account, please ignore this mail.
                              </p>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>

                  <!-- END MAIN CONTENT AREA -->
                </tbody>
              </table>

              <!-- START FOOTER -->
              <div class="footer" style="clear: both;margin-top: 10px;text-align: center;width: 100%;">
                <table role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate;mso-table-lspace: 0pt;mso-table-rspace: 0pt;width: 100%;">
                  <tbody>
                    <tr>
                      <td class="content-block powered-by" style="font-family: sans-serif;font-size: 12px;vertical-align: top;padding-bottom: 10px;padding-top: 10px;color: #999999;text-align: center;">
                        Powered by CityStoryTracking.
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <!-- END FOOTER -->

              <!-- END CENTERED WHITE CONTAINER -->
            </div>
          </td>
          <td style="font-family: sans-serif;font-size: 14px;vertical-align: top;"> </td>
        </tr>
      </tbody>
    </table>
  </xsl:template>
</xsl:stylesheet>